siteTitle = "Stough.Codes"
siteDescr = "Software Developer. Electrical Engineer. Hopeless Technologist. Professional Human."
siteAuthor = "Dan Stough"

siteGithubUrl = "https://github.com/DanStough"
siteLinkedinUrl = "https://www.linkedin.com/in/danstough/"
siteEmailUrl = "Dan@Stough.codes"


googleAnalyticsId = ""

linkPrefix = "/"